/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MaintenanceToggleRouteImport } from './routes/maintenance-toggle'
import { Route as SubsidiariesRouteImport } from './routes/subsidiaries'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutCeoRouteImport } from './routes/about/ceo'
import { Route as AboutOrganizationRouteImport } from './routes/about/organization'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as CareerIndexRouteImport } from './routes/career/index'
import { Route as ServicesConstructionRouteImport } from './routes/services/construction'
import { Route as ServicesEnergyRouteImport } from './routes/services/energy'
import { Route as ServicesMiningRouteImport } from './routes/services/mining'
import { Route as ServicesOilAndGasRouteImport } from './routes/services/oil-and-gas'
import { Route as ServicesOtherServicesRouteImport } from './routes/services/other-services'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminJobsNewRouteImport } from './routes/admin/jobs/new'
import { Route as ServicesDetailsSlugRouteImport } from './routes/services/details.$slug'
import { Route as ServicesPowerIndexRouteImport } from './routes/services/power/index'
import { Route as ServicesPowerThermalEnergyRouteImport } from './routes/services/power/thermal-energy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceToggleRoute = MaintenanceToggleRouteImport.update({
  id: '/maintenance-toggle',
  path: '/maintenance-toggle',
  getParentRoute: () => rootRouteImport,
} as any)
const SubsidiariesRoute = SubsidiariesRouteImport.update({
  id: '/subsidiaries',
  path: '/subsidiaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCeoRoute = AboutCeoRouteImport.update({
  id: '/about/ceo',
  path: '/about/ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOrganizationRoute = AboutOrganizationRouteImport.update({
  id: '/about/organization',
  path: '/about/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerIndexRoute = CareerIndexRouteImport.update({
  id: '/career/',
  path: '/career/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesConstructionRoute = ServicesConstructionRouteImport.update({
  id: '/services/construction',
  path: '/services/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEnergyRoute = ServicesEnergyRouteImport.update({
  id: '/services/energy',
  path: '/services/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMiningRoute = ServicesMiningRouteImport.update({
  id: '/services/mining',
  path: '/services/mining',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOilAndGasRoute = ServicesOilAndGasRouteImport.update({
  id: '/services/oil-and-gas',
  path: '/services/oil-and-gas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOtherServicesRoute = ServicesOtherServicesRouteImport.update({
  id: '/services/other-services',
  path: '/services/other-services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/admin/jobs/',
  path: '/admin/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsNewRoute = AdminJobsNewRouteImport.update({
  id: '/admin/jobs/new',
  path: '/admin/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDetailsSlugRoute = ServicesDetailsSlugRouteImport.update({
  id: '/services/details/$slug',
  path: '/services/details/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPowerIndexRoute = ServicesPowerIndexRouteImport.update({
  id: '/services/power/',
  path: '/services/power/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPowerThermalEnergyRoute =
  ServicesPowerThermalEnergyRouteImport.update({
    id: '/services/power/thermal-energy',
    path: '/services/power/thermal-energy',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/maintenance-toggle': typeof MaintenanceToggleRoute
  '/subsidiaries': typeof SubsidiariesRoute
  '/about/ceo': typeof AboutCeoRoute
  '/about/organization': typeof AboutOrganizationRoute
  '/admin/login': typeof AdminLoginRoute
  '/services/construction': typeof ServicesConstructionRoute
  '/services/energy': typeof ServicesEnergyRoute
  '/services/mining': typeof ServicesMiningRoute
  '/services/oil-and-gas': typeof ServicesOilAndGasRoute
  '/services/other-services': typeof ServicesOtherServicesRoute
  '/about/': typeof AboutIndexRoute
  '/career/': typeof CareerIndexRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/services/details/$slug': typeof ServicesDetailsSlugRoute
  '/services/power/thermal-energy': typeof ServicesPowerThermalEnergyRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/services/power/': typeof ServicesPowerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/maintenance-toggle': typeof MaintenanceToggleRoute
  '/subsidiaries': typeof SubsidiariesRoute
  '/about/ceo': typeof AboutCeoRoute
  '/about/organization': typeof AboutOrganizationRoute
  '/admin/login': typeof AdminLoginRoute
  '/services/construction': typeof ServicesConstructionRoute
  '/services/energy': typeof ServicesEnergyRoute
  '/services/mining': typeof ServicesMiningRoute
  '/services/oil-and-gas': typeof ServicesOilAndGasRoute
  '/services/other-services': typeof ServicesOtherServicesRoute
  '/about': typeof AboutIndexRoute
  '/career': typeof CareerIndexRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/services/details/$slug': typeof ServicesDetailsSlugRoute
  '/services/power/thermal-energy': typeof ServicesPowerThermalEnergyRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/services/power': typeof ServicesPowerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/maintenance-toggle': typeof MaintenanceToggleRoute
  '/subsidiaries': typeof SubsidiariesRoute
  '/about/ceo': typeof AboutCeoRoute
  '/about/organization': typeof AboutOrganizationRoute
  '/admin/login': typeof AdminLoginRoute
  '/services/construction': typeof ServicesConstructionRoute
  '/services/energy': typeof ServicesEnergyRoute
  '/services/mining': typeof ServicesMiningRoute
  '/services/oil-and-gas': typeof ServicesOilAndGasRoute
  '/services/other-services': typeof ServicesOtherServicesRoute
  '/about/': typeof AboutIndexRoute
  '/career/': typeof CareerIndexRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/services/details/$slug': typeof ServicesDetailsSlugRoute
  '/services/power/thermal-energy': typeof ServicesPowerThermalEnergyRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/services/power/': typeof ServicesPowerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/maintenance-toggle'
    | '/subsidiaries'
    | '/about/ceo'
    | '/about/organization'
    | '/admin/login'
    | '/services/construction'
    | '/services/energy'
    | '/services/mining'
    | '/services/oil-and-gas'
    | '/services/other-services'
    | '/about/'
    | '/career/'
    | '/admin/jobs/new'
    | '/services/details/$slug'
    | '/services/power/thermal-energy'
    | '/admin/jobs/'
    | '/services/power/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/maintenance-toggle'
    | '/subsidiaries'
    | '/about/ceo'
    | '/about/organization'
    | '/admin/login'
    | '/services/construction'
    | '/services/energy'
    | '/services/mining'
    | '/services/oil-and-gas'
    | '/services/other-services'
    | '/about'
    | '/career'
    | '/admin/jobs/new'
    | '/services/details/$slug'
    | '/services/power/thermal-energy'
    | '/admin/jobs'
    | '/services/power'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/maintenance-toggle'
    | '/subsidiaries'
    | '/about/ceo'
    | '/about/organization'
    | '/admin/login'
    | '/services/construction'
    | '/services/energy'
    | '/services/mining'
    | '/services/oil-and-gas'
    | '/services/other-services'
    | '/about/'
    | '/career/'
    | '/admin/jobs/new'
    | '/services/details/$slug'
    | '/services/power/thermal-energy'
    | '/admin/jobs/'
    | '/services/power/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  MaintenanceToggleRoute: typeof MaintenanceToggleRoute
  SubsidiariesRoute: typeof SubsidiariesRoute
  AboutCeoRoute: typeof AboutCeoRoute
  AboutOrganizationRoute: typeof AboutOrganizationRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ServicesConstructionRoute: typeof ServicesConstructionRoute
  ServicesEnergyRoute: typeof ServicesEnergyRoute
  ServicesMiningRoute: typeof ServicesMiningRoute
  ServicesOilAndGasRoute: typeof ServicesOilAndGasRoute
  ServicesOtherServicesRoute: typeof ServicesOtherServicesRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CareerIndexRoute: typeof CareerIndexRoute
  AdminJobsNewRoute: typeof AdminJobsNewRoute
  ServicesDetailsSlugRoute: typeof ServicesDetailsSlugRoute
  ServicesPowerThermalEnergyRoute: typeof ServicesPowerThermalEnergyRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  ServicesPowerIndexRoute: typeof ServicesPowerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance-toggle': {
      id: '/maintenance-toggle'
      path: '/maintenance-toggle'
      fullPath: '/maintenance-toggle'
      preLoaderRoute: typeof MaintenanceToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subsidiaries': {
      id: '/subsidiaries'
      path: '/subsidiaries'
      fullPath: '/subsidiaries'
      preLoaderRoute: typeof SubsidiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/ceo': {
      id: '/about/ceo'
      path: '/about/ceo'
      fullPath: '/about/ceo'
      preLoaderRoute: typeof AboutCeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/organization': {
      id: '/about/organization'
      path: '/about/organization'
      fullPath: '/about/organization'
      preLoaderRoute: typeof AboutOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/': {
      id: '/career/'
      path: '/career'
      fullPath: '/career/'
      preLoaderRoute: typeof CareerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/construction': {
      id: '/services/construction'
      path: '/services/construction'
      fullPath: '/services/construction'
      preLoaderRoute: typeof ServicesConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/energy': {
      id: '/services/energy'
      path: '/services/energy'
      fullPath: '/services/energy'
      preLoaderRoute: typeof ServicesEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mining': {
      id: '/services/mining'
      path: '/services/mining'
      fullPath: '/services/mining'
      preLoaderRoute: typeof ServicesMiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/oil-and-gas': {
      id: '/services/oil-and-gas'
      path: '/services/oil-and-gas'
      fullPath: '/services/oil-and-gas'
      preLoaderRoute: typeof ServicesOilAndGasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/other-services': {
      id: '/services/other-services'
      path: '/services/other-services'
      fullPath: '/services/other-services'
      preLoaderRoute: typeof ServicesOtherServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/admin/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/new': {
      id: '/admin/jobs/new'
      path: '/admin/jobs/new'
      fullPath: '/admin/jobs/new'
      preLoaderRoute: typeof AdminJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/details/$slug': {
      id: '/services/details/$slug'
      path: '/services/details/$slug'
      fullPath: '/services/details/$slug'
      preLoaderRoute: typeof ServicesDetailsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/power/': {
      id: '/services/power/'
      path: '/services/power'
      fullPath: '/services/power/'
      preLoaderRoute: typeof ServicesPowerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/power/thermal-energy': {
      id: '/services/power/thermal-energy'
      path: '/services/power/thermal-energy'
      fullPath: '/services/power/thermal-energy'
      preLoaderRoute: typeof ServicesPowerThermalEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  MaintenanceToggleRoute: MaintenanceToggleRoute,
  SubsidiariesRoute: SubsidiariesRoute,
  AboutCeoRoute: AboutCeoRoute,
  AboutOrganizationRoute: AboutOrganizationRoute,
  AdminLoginRoute: AdminLoginRoute,
  ServicesConstructionRoute: ServicesConstructionRoute,
  ServicesEnergyRoute: ServicesEnergyRoute,
  ServicesMiningRoute: ServicesMiningRoute,
  ServicesOilAndGasRoute: ServicesOilAndGasRoute,
  ServicesOtherServicesRoute: ServicesOtherServicesRoute,
  AboutIndexRoute: AboutIndexRoute,
  CareerIndexRoute: CareerIndexRoute,
  AdminJobsNewRoute: AdminJobsNewRoute,
  ServicesDetailsSlugRoute: ServicesDetailsSlugRoute,
  ServicesPowerThermalEnergyRoute: ServicesPowerThermalEnergyRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  ServicesPowerIndexRoute: ServicesPowerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
